version: 2.1

orbs:
  node: circleci/node@5.0.3

# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy over SSH
          command: |
            scp -r ./.output ./ecosystem.config.js $USER@$IP:/home/circleci/sozle && ssh $USER@$IP "pm2 restart sozle/ecosystem.config.js"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
